// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.mattermost.mailermost-plugin",
	Version: "0.0.7",
}
